[package]
name = "image-downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
console = "0.15.5"
dialoguer = "0.10.3"

[profile.release]
panic = "abort"
